### ISSUE TITLE
Stops Running after "Found XXXX movies"

### ISSUE THREAD

**Issue by vexersa** [artagel/radarr-genre-filter#1]
Firstly, thanks for the script, it is super handy. 

After running the script successfully this morning and getting rid of the myriad garbage horror films from lists, I wanted to get the script running as a cron job. 

I created a simple wrapper script and ran it manually to test if all was ok. 

Everything looked to be working, but now whenever I run run_radarr_filter.py the script seems to stop after "Found xxxx movies" 

EG:

``python run_radarr_filter.py -f War -d -v
[+] Getting your list of movies from Radarr
[+] Found 2721 movies
``

I am running the script in a pipenv python 3 environment with environmental variables configured to suit the requirements of settings.py.

Not sure what's up, but nothing has changed elsewhere.

**Comment by artagel** [comment]
That looks right. The script tracks the last ID it checked.  Any new movie added will have a newer ID, so we don’t need to check the ones we did before again. You should have the file in the link below with a number in it, probably that number is roughly about the number of movies found, but won’t match exactly as the ID increments and we know we deleted movies.  
https://github.com/artagel/radarr-genre-filter/blob/4446f5a14bc0718081006e71ea5c164c448e09bf/settings.py#L20
